#!/usr/bin/env python3

Set1 = 'ATGGCCCTGTGGACACGCCTGGTGCCCCTGCTGGCCCTGCTGGCACTCTGGGCCCCCGCC'

Set2 = 'ATGGCCTTCTGGCTCCAAGCTGCATCTCTGCTGGTGTTGCTGGCGCTCTCCCCCGGGGTA'

Counter = []
pointer = []
for i in range(len(Set1)+1):
    Counter += [[-i]]
    pointer += [[None]]
for j in range(1,len(Set2)+1):
    for i in range(len(Set1)+1):
        if i == 0:
            Colcount = [[-j]]
            Pointcount = [[None]]
        else:
            if j == 1:
                options = {'L': Counter[i][0] - 1, 'D': Counter[i-1][0], 'T': Colcount[i-1][0] - 1}
            else:
                options = {'L': Counter[i][j-1] - 1, 'D': Counter[i-1][j-1], 'T': Colcount[i-1][0] - 1}
            if Set1[i-1] == Set2[j-1]:
                options['D'] += 1
            else:
                options['D'] -= 1
            highval = sorted(options.values(), reverse = True)
            highkey = sorted(options.keys(), key=options.get, reverse = True)
            Colcount += [[highval[0]]]
            if highval[0] != highval[1]:
                Pointcount += [[highkey[0]]]
            elif highval[1] == highval[2]:
                Pointcount += [[highkey]]
            else:
                Pointcount += [[highkey[0:1]]]
    for elem in enumerate(Colcount):
        Counter[elem[0]].append(elem[1])
    for elem in enumerate(Pointcount):
        pointer[elem[0]].append(elem[1])
